# Generated by Django 2.1.2 on 2019-05-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_auto_20190529_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.City')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.District')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.City')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.District')),
            ],
        ),
        migrations.RemoveField(
            model_name='court',
            name='city',
        ),
        migrations.RemoveField(
            model_name='court',
            name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.Street'),
        ),
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.Address'),
        ),
    ]
