# Generated by Django 2.1.2 on 2019-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_auto_20190529_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='city',
        ),
        migrations.RemoveField(
            model_name='street',
            name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='building',
            new_name='address2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(default='street, section ...', max_length=50),
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
