# Generated by Django 2.1.2 on 2019-05-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20190529_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=50),
        ),
    ]
