# Generated by Django 2.1.2 on 2019-05-30 02:45

import courts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_auto_20190529_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=courts.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='courts.Court')),
            ],
        ),
        migrations.RemoveField(
            model_name='courtimage',
            name='court',
        ),
        migrations.DeleteModel(
            name='CourtImage',
        ),
    ]
