# Generated by Django 2.1.2 on 2019-06-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_auto_20190530_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_address', to='courts.Address'),
        ),
    ]
