# Generated by Django 2.1.2 on 2019-06-12 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0009_auto_20190611_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
