# Generated by Django 2.1.2 on 2019-06-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0010_court_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtphoto',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
