# Generated by Django 2.1.2 on 2019-06-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0011_auto_20190612_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courtphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
