# Generated by Django 2.1.2 on 2019-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0014_auto_20190612_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
