# Generated by Django 2.1.2 on 2019-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0015_court_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='court',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
