# Generated by Django 2.1.2 on 2019-06-28 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0018_auto_20190628_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end',
            field=models.PositiveIntegerField(default=23, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
