# Generated by Django 2.1.2 on 2019-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0020_auto_20190628_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.CharField(max_length=5),
        ),
    ]
