# Generated by Django 2.1.2 on 2019-06-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0021_auto_20190628_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.CharField(default='22:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.CharField(default='08:00', max_length=5),
        ),
    ]
