# Generated by Django 2.1.2 on 2019-07-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0022_auto_20190628_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
