# Generated by Django 2.1.2 on 2019-07-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0027_auto_20190702_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('H', 'Half'), ('F', 'Full')], default='1', max_length=1),
        ),
    ]
