# Generated by Django 2.1.2 on 2019-07-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0028_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('H', 'Half'), ('F', 'Full')], default='H', max_length=1),
        ),
    ]
