# Generated by Django 2.1.2 on 2019-07-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0029_auto_20190702_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='left_court',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='right_court',
            field=models.BooleanField(default=False),
        ),
    ]
